apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: flame
build:
  artifacts:
  - image: ghcr.io/joshndroid/flame-switch
    context: .
    sync:
      manual:
      - src: controllers/*.js
        dest: .
    docker:
      dockerfile: .docker/Dockerfile.kubernetes
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: ghcr.io/joshndroid/flame-switch
      sync:
        manual:
        - src: controllers/*.js
          dest: .
      docker:
        dockerfile: .docker/Dockerfile.kubernetes
- name: shokohsc
  build:
    artifacts:
    - image: ghcr.io/joshndroid/flame-switch
      sync:
        manual:
        - src: controllers/*.js
          dest: .
      kaniko:
        dockerfile: .docker/Dockerfile.kubernetes
        cache:
          repo: shokohsc/flame
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
  deploy:
    kustomize:
      paths:
      - k8s/overlays/shokohsc
- name: prod
  build:
    artifacts:
    - image: ghcr.io/joshndroid/flame-switch
      kaniko:
        dockerfile: .docker/Dockerfile
        cache:
          repo: shokohsc/flame
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
